# Site settings
title: "Baroness Nuala O'Loan DBE MRIA"
author: "Baroness Nuala O'Loan DBE MRIA"
description: "The official website of Baroness Nuala O'Loan DBE MRIA"
email: oloann@parliament.uk
open-source: "Open Source"
hero: "/images/ian_knox_cartoon.jpg"

baseurl: # the subpath of your site, e.g. /blog/
url: http://nualaoloan.com/ # the base hostname & protocol for your site
paginate: 5

# Gems
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# Set URL structure for categories and their posts
permalink: /:categories/:title/
